version: '3.7'
services:
  db:
    build:
      context: .docker/pgsql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 54321:54321
    volumes:
      - .docker/logs/postgresql/:/var/log/postgresql
  adminer:
    image: adminer:4.7.6-standalone
    ports:
      - 8888:8888
  nginx:
    build:
      context: .docker/nginx
    volumes:
      - .:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/sites-available
      - .docker/logs/nginx/:/var/log/nginx
    ports:
      - 88:88
